//! Generated by `aomi-build gen-client okx`.
//! Do not edit by hand — re-run with --force to regenerate.
//!
//! Hand-written companions (signing helpers, etc.) live next to this file
//! in `auth.rs` or other sibling modules.

pub mod auth;
#[allow(clippy::all, dead_code, unused_imports)]
pub mod client;

pub use auth::{iso_timestamp, sign};
pub use client::*;
