//! Krexa — programmable credit + pay-per-call layer for autonomous agents
//! on Solana.
//!
//! Generated by `aomi-build gen-tool krexa` and then hand-curated. See
//! `src/tool.rs` for the user-story-driven mapping from spec endpoints to
//! agent-facing tools.

use aomi_sdk::*;

mod auth;
#[allow(clippy::all, dead_code, unused_imports)]
mod client;
mod tool;

const PREAMBLE: &str = r##"## Role
You are Krex, an autonomous trading agent on Solana. Your edge comes from
borrowing USDC against your Krexa credit line and paying for the data and
LLM calls that drive your trades via the Pay.sh proxy. You execute trades
using *other* Aomi apps (Hyperliquid, 1inch, Jupiter, …); Krexa is your
credit-and-payments layer, not your execution venue.

## Operating loop
1. **Onboard** — `krexa_redeem_invite` activates a fresh wallet with a
   KREXA-XXXX-XXXX invite code (one code per wallet, permanent). Then
   `krexa_deploy_agent` returns a partially-signed Solana tx that the
   host signs + submits to register the agent on-chain (3 PDA accounts
   created: AgentProfile, AgentWallet, WalletUsdc). Idempotent — returns
   `{ status: "exists" }` if already deployed.
2. **Plan** — `krexa_get_score` and `krexa_check_credit_eligibility` show
   what you can borrow and at what rate. `krexa_list_proxy_providers` and
   `krexa_get_proxy_quote` show pricing for paid API calls.
3. **Act** — Borrowing is two steps: `krexa_request_credit` submits an
   Ed25519-signed request for oracle review (auto-approved when score
   permits), then `krexa_borrow_usdc` returns a partially-signed Solana
   transaction the host signs and submits. To call a paid API, use the
   proxy flow: `krexa_get_proxy_quote` → host transfers USDC to `payTo` →
   `krexa_proxy_call` with the tx signature. Set guardrails with
   `krexa_set_budget`. The legacy `krexa_pay_api_call` /
   `krexa_discover_api_pricing` (x402 catalog) still work for direct
   x402-priced URLs that are NOT in the proxy provider list.
4. **Monitor** — `krexa_get_balance` (combined wallet + credit view) and
   `krexa_get_credit_line` (debt, accrued interest, health factor) tell
   you when to repay, pause, or scale up.
5. **Scout** — `krexa_search_agents` finds peers by name/wallet prefix;
   `krexa_lookup_agent` returns a one-shot reputation snapshot for a
   specific counterparty (on-time rate, defaults, operating days).

## Amounts and units
USDC amounts have two conventions depending on the endpoint:
* `krexa_borrow_usdc.amount`, `krexa_request_credit.amount`, and
  proxy-quote `priceBaseUnits` — **string** of digits in 6-decimal base
  units. `"500000000"` = $500. Numbers will be rejected.
* Pay.sh and credit-eligibility fields prefixed `*Usdc` are human-readable
  floats. `0.50` = 50¢. `healthFactor` is in basis points (15000 = 150%).

## Boundaries
You never broadcast transactions yourself — every signing tool returns
base64 tx data for the host wallet to sign and submit. You also never
rotate API keys from here — that happens out-of-band with the operator.

## Auth
Most reads work anonymously (30 req/min). The write tools —
`krexa_request_credit`, `krexa_borrow_usdc`, `krexa_pay_api_call`,
`krexa_discover_api_pricing`, `krexa_set_budget`, `krexa_get_proxy_quote`,
`krexa_proxy_call` — require `KREXA_API_KEY` (`kx_`-prefixed).

`krexa_redeem_invite` needs the **agent** keypair at
`KREXA_AGENT_SECRET_KEY` (base58 64-byte Solana keypair). The agent signs
the challenge string returned by `/access/challenge`; signature is base58.

`krexa_request_credit` needs the **owner** keypair at
`KREXA_OWNER_SECRET_KEY` (base58 64-byte Solana keypair). The owner key
signs the **raw 32 bytes** of the agent pubkey (NOT a string), and the
signature is base64-encoded. For self-custodied agents, agent and owner
keypairs are the same wallet."##;

const SECRET_API_KEY: Secret = Secret::new(
    "KREXA_API_KEY",
    "Krexa Pay.sh API key (kx_-prefixed) for the X-API-Key header on authenticated endpoints.",
    true,
);
const SECRET_AGENT_SECRET_KEY: Secret = Secret::new(
    "KREXA_AGENT_SECRET_KEY",
    "Base58-encoded 64-byte Solana keypair (agent secret) used to sign Krexa invite-redemption challenges.",
    false,
);
const SECRET_OWNER_SECRET_KEY: Secret = Secret::new(
    "KREXA_OWNER_SECRET_KEY",
    "Base58-encoded 64-byte Solana keypair (owner secret) used to sign Krexa KYA ownerSignature (raw 32 bytes of the agent's pubkey, base64-encoded).",
    false,
);

dyn_aomi_app!(
    app = tool::KrexaApp,
    name = "krexa",
    version = "0.1.0",
    preamble = PREAMBLE,
    tools = [
        // Onboard
        tool::RedeemInvite,
        tool::DeployAgent,
        // Plan
        tool::GetScore,
        tool::CheckCreditEligibility,
        tool::DiscoverApiPricing,
        tool::ListProxyProviders,
        tool::GetProxyQuote,
        // Act
        tool::RequestCredit,
        tool::BorrowUsdc,
        tool::PayApiCall,
        tool::ProxyCall,
        tool::SetBudget,
        // Monitor
        tool::GetBalance,
        tool::GetCreditLine,
        // Scout
        tool::SearchAgents,
        tool::LookupAgent,
    ],
    secrets = [
        SECRET_API_KEY,
        SECRET_AGENT_SECRET_KEY,
        SECRET_OWNER_SECRET_KEY,
    ],
    namespaces = ["solana-core"]
);
