use std::fmt::Write;

use super::{Mode, Op, ParamKind, ParamLoc, ResponseSummary};

pub fn cargo_toml(platform: &str, mode: Mode) -> String {
    let provider_dep_block = match mode {
        Mode::Shared => {
            format!("aomi-ext = {{ path = \"../../ext\", features = [\"{platform}\"] }}\n")
        }
        Mode::AppLocal => {
            // App-local: client deps live directly here. Detect from the
            // generated client source which optional crates progenitor pulled
            // in (uuid for `format: uuid`, regress for `pattern:` constraints).
            let client_path = format!("apps/{platform}/src/client/client.rs");
            let src = std::fs::read_to_string(&client_path).unwrap_or_default();
            let mut block = String::from(
                "progenitor-client = \"0.14\"\n\
                 chrono = { version = \"0.4\", features = [\"serde\"] }\n",
            );
            if src.contains("uuid::") {
                block.push_str("uuid = { version = \"1\", features = [\"serde\", \"v4\"] }\n");
            }
            if src.contains("regress::") {
                block.push_str("regress = \"0.10\"\n");
            }
            block
        }
    };
    format!(
        r#"[package]
name = "{platform}"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
aomi-sdk = {{ path = "../../sdk" }}
{provider_dep_block}# Match progenitor-client's reqwest version so curated tool layers can wrap
# `Client::new_with_client(...)` with header-injecting middleware for auth.
reqwest = {{ version = "0.13", default-features = false, features = ["json", "rustls"] }}
schemars = "1.0.4"
serde = {{ version = "1.0", features = ["derive"] }}
serde_json = "1.0"
tokio = {{ version = "1", features = ["rt-multi-thread", "macros"] }}
"#
    )
}

pub fn preamble_default(platform: &str) -> String {
    format!(
        "## Role\nYou are an AI assistant for the {platform} API. Tools below wrap the official OpenAPI surface."
    )
}

pub fn lib_rs(platform: &str, app_struct: &str, ops: &[Op], preamble: &str, mode: Mode) -> String {
    let tool_list = ops
        .iter()
        .map(|o| format!("        tool::{},", o.tool_marker))
        .collect::<Vec<_>>()
        .join("\n");
    let mut out = String::new();
    let _ = writeln!(
        out,
        "//! Generated by `aomi-build gen-tool {platform}`. Tool definitions are\n\
         //! starting points — edit `src/tool.rs` to refine names, descriptions, and\n\
         //! response shaping."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "use aomi_sdk::*;");
    let _ = writeln!(out);
    if mode == Mode::AppLocal {
        // Generated client lives at apps/<platform>/src/client/
        let _ = writeln!(out, "#[allow(clippy::all, dead_code, unused_imports)]");
        let _ = writeln!(out, "mod client;");
    }
    let _ = writeln!(out, "mod tool;");
    let _ = writeln!(out);
    let _ = writeln!(out, "const PREAMBLE: &str = r##\"{preamble}\"##;");
    let _ = writeln!(out);
    let _ = writeln!(out, "dyn_aomi_app!(");
    let _ = writeln!(out, "    app = tool::{app_struct},");
    let _ = writeln!(out, "    name = \"{platform}\",");
    let _ = writeln!(out, "    version = \"0.1.0\",");
    let _ = writeln!(out, "    preamble = PREAMBLE,");
    let _ = writeln!(out, "    tools = [");
    let _ = writeln!(out, "{tool_list}");
    let _ = writeln!(out, "    ],");
    let _ = writeln!(out, "    namespaces = [\"evm-core\"]");
    let _ = writeln!(out, ");");
    out
}

pub fn tool_rs(platform: &str, app_struct: &str, ops: &[Op], mode: Mode) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "//! Generated by `aomi-build gen-tool {platform}`. Each tool is a stub:\n\
         //! the wiring works (params → builder → send → JSON) but you should\n\
         //! review tool names, descriptions, and any auth assumptions."
    );
    let _ = writeln!(out);
    let (client_use, types_use) = match mode {
        Mode::Shared => (
            format!("use aomi_ext::{platform}::Client as GenClient;"),
            format!("#[allow(unused_imports)]\nuse aomi_ext::{platform}::types::*;"),
        ),
        Mode::AppLocal => (
            "use crate::client::Client as GenClient;".to_string(),
            "#[allow(unused_imports)]\nuse crate::client::types::*;".to_string(),
        ),
    };
    let _ = writeln!(out, "{client_use}");
    let _ = writeln!(out, "{types_use}");
    let _ = writeln!(out, "use aomi_sdk::*;");
    let _ = writeln!(out, "use aomi_sdk::schemars::JsonSchema;");
    let _ = writeln!(out, "use serde::{{Deserialize, Serialize}};");
    let _ = writeln!(out, "use serde_json::Value;");
    let _ = writeln!(out);
    let _ = writeln!(out, "#[derive(Clone, Default)]");
    let _ = writeln!(out, "pub(crate) struct {app_struct};");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "fn ok<T: Serialize>(value: T) -> Result<Value, String> {{"
    );
    let _ = writeln!(
        out,
        "    let value = serde_json::to_value(value).map_err(|e| format!(\"[{platform}] serialize: {{e}}\"))?;"
    );
    let _ = writeln!(out, "    Ok(match value {{");
    let _ = writeln!(out, "        Value::Object(mut m) => {{");
    let _ = writeln!(
        out,
        "            m.insert(\"source\".into(), Value::String(\"{platform}\".into()));"
    );
    let _ = writeln!(out, "            Value::Object(m)");
    let _ = writeln!(out, "        }}");
    let _ = writeln!(
        out,
        "        other => serde_json::json!({{ \"source\": \"{platform}\", \"data\": other }}),"
    );
    let _ = writeln!(out, "    }})");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "fn rt() -> Result<tokio::runtime::Runtime, String> {{");
    let _ = writeln!(
        out,
        "    tokio::runtime::Runtime::new().map_err(|e| format!(\"[{platform}] runtime: {{e}}\"))"
    );
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);

    for op in ops {
        emit_tool(&mut out, platform, app_struct, op);
    }
    out
}

fn emit_tool(out: &mut String, platform: &str, app_struct: &str, op: &Op) {
    let tool_name = format!("{platform}_{}", op.operation_id);
    let args_struct = format!("{}Args", op.tool_marker);
    let env_var = format!("{}_API_KEY", platform.to_uppercase());

    let summary = op
        .summary
        .clone()
        .or_else(|| op.description.clone())
        .unwrap_or_else(|| format!("{} {}", op.method.to_uppercase(), op.path));
    let description = sanitize_one_liner(&summary);

    let _ = writeln!(
        out,
        "// ============================================================"
    );
    let _ = writeln!(out, "// {} {}", op.method.to_uppercase(), op.path);
    let _ = writeln!(
        out,
        "// ============================================================"
    );
    let _ = writeln!(out);

    let _ = writeln!(out, "pub(crate) struct {};", op.tool_marker);
    let _ = writeln!(out);

    // Args struct
    let _ = writeln!(out, "#[derive(Debug, Deserialize, JsonSchema)]");
    let _ = writeln!(out, "pub(crate) struct {args_struct} {{");
    let mut emitted_auth = false;
    for p in &op.params {
        if p.is_auth {
            if emitted_auth {
                continue;
            }
            emitted_auth = true;
            let _ = writeln!(
                out,
                "    /// API credential (falls back to env var {env_var}).",
            );
            let _ = writeln!(out, "    pub api_key: Option<String>,");
        } else {
            if let Some(d) = &p.description {
                let _ = writeln!(out, "    /// {}", sanitize_one_liner(d));
            }
            let rust_ty = if p.required {
                rust_type(p.kind).to_string()
            } else {
                format!("Option<{}>", rust_type(p.kind))
            };
            let _ = writeln!(out, "    pub {}: {},", p.snake_name, rust_ty);
        }
    }
    if op.has_request_body {
        let _ = writeln!(
            out,
            "    // TODO: typed body — generated client expects aomi_ext::{platform}::types::*."
        );
        let _ = writeln!(
            out,
            "    // Add `pub body: <T>` and edit `run` to pass it to req.body(...)."
        );
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);

    // Impl
    let _ = writeln!(out, "impl DynAomiTool for {} {{", op.tool_marker);
    let _ = writeln!(out, "    type App = {app_struct};");
    let _ = writeln!(out, "    type Args = {args_struct};");
    let _ = writeln!(out, "    const NAME: &'static str = \"{tool_name}\";");
    let _ = writeln!(
        out,
        "    const DESCRIPTION: &'static str = \"{description}\";"
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "    fn run(_app: &{app_struct}, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {{"
    );

    // Auth resolution (first auth param only — multi-auth needs hand-editing)
    let auth = op.params.iter().find(|p| p.is_auth);
    if let Some(a) = auth {
        let _ = writeln!(
            out,
            "        let api_key = resolve_secret_value(args.api_key.as_deref(), \"{env_var}\", \"[{platform}] missing api_key argument and {env_var} env var\")?;"
        );
        let _ = a; // silence unused
    }

    let _ = writeln!(
        out,
        "        let client = GenClient::new(\"{}\");",
        op.server_url
    );
    let _ = writeln!(out, "        let runtime = rt()?;");
    let _ = writeln!(out, "        let result = runtime.block_on(async move {{");
    let mut call_args: Vec<String> = Vec::new();
    let mut applied_auth = false;
    for p in &op.params {
        let expr = if p.is_auth {
            if !applied_auth {
                applied_auth = true;
                if p.required {
                    "api_key.as_str()".to_string()
                } else {
                    "Some(api_key.as_str())".to_string()
                }
            } else if p.required {
                // Second required auth slot — same key. Rare.
                "api_key.as_str()".to_string()
            } else {
                "None".to_string()
            }
        } else if p.required {
            match p.kind {
                ParamKind::String | ParamKind::Other => format!("args.{}.as_str()", p.snake_name),
                _ => format!("args.{}", p.snake_name),
            }
        } else {
            match p.kind {
                ParamKind::String | ParamKind::Other => format!("args.{}.as_deref()", p.snake_name),
                _ => format!("args.{}", p.snake_name),
            }
        };
        call_args.push(expr);
    }
    if op.has_request_body {
        call_args.push("/* TODO: typed body */ todo!()".to_string());
    }
    let args_str = if call_args.is_empty() {
        String::new()
    } else if call_args.iter().map(|s| s.len()).sum::<usize>() < 60 {
        call_args.join(", ")
    } else {
        format!(
            "\n                {}\n            ",
            call_args.join(",\n                ")
        )
    };
    // Progenitor snake_cases method names; operation_id is often camelCase.
    let method_ident = crate::spec_load::snake_case(&op.operation_id);
    let _ = writeln!(
        out,
        "            client.{}({}).await",
        method_ident, args_str
    );
    let _ = writeln!(
        out,
        "        }}).map_err(|e| format!(\"[{platform}] {}: {{e}}\"))?;",
        method_ident
    );
    // Per-op response-shape comment. The `types::*` glob at the top of the
    // file makes the named type immediately accessible. Trim noisy fields by
    // editing the spec — never by adding a *Summary projection here.
    match &op.response_summary {
        ResponseSummary::Typed { rust_type } => {
            let _ = writeln!(
                out,
                "        // Response: `{rust_type}` (typed). Forward as-is — the typed struct"
            );
            let _ = writeln!(
                out,
                "        // IS what the LLM sees. If it carries fields the LLM doesn't act on"
            );
            let _ = writeln!(
                out,
                "        // (logoURI, audits, extensions, …), drop them from the response schema"
            );
            let _ = writeln!(
                out,
                "        // in ext/specs/{platform}.yaml and `aomi-build gen-client --force`."
            );
        }
        ResponseSummary::Loose => {
            let _ = writeln!(
                out,
                "        // Response: `Map<String, Value>` — spec marked `additionalProperties: true`."
            );
            let _ = writeln!(
                out,
                "        // Tighten via: capture real samples to ext/specs/{platform}.samples/,"
            );
            let _ = writeln!(
                out,
                "        // run `aomi-build tighten-spec {platform}`, then gen-client --force."
            );
        }
        ResponseSummary::Bytes => {
            let _ = writeln!(
                out,
                "        // Response: bytes (non-JSON content type). Decode + summarise as needed."
            );
        }
    }
    let _ = writeln!(out, "        ok(result.into_inner())");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
}

fn rust_type(k: ParamKind) -> &'static str {
    match k {
        ParamKind::String => "String",
        ParamKind::Int32 => "i32",
        ParamKind::Int64 => "i64",
        ParamKind::Number => "f64",
        ParamKind::Boolean => "bool",
        // EnumString shouldn't reach the renderer (op gets skipped earlier),
        // but fall back to String defensively.
        ParamKind::EnumString | ParamKind::Other => "String",
    }
}

fn sanitize_one_liner(s: &str) -> String {
    s.lines()
        .next()
        .unwrap_or("")
        .trim()
        .replace('"', "'")
        .replace('\\', "\\\\")
}

// silence unused-import warning in render.rs — ParamLoc reserved for future.
#[allow(dead_code)]
fn _hold(_: ParamLoc) {}
