//! Generated by `aomi-build gen-tool pelagos`. Tool definitions are
//! starting points — edit `src/tool.rs` to refine names, descriptions, and
//! response shaping.

use aomi_sdk::*;

#[allow(clippy::all, dead_code, unused_imports)]
mod client;
mod tool;

const PREAMBLE: &str = r##"## Role
You are an AI assistant for the pelagos API. Tools below wrap the official OpenAPI surface."##;

dyn_aomi_app!(
    app = tool::PelagosApp,
    name = "pelagos",
    version = "0.1.0",
    preamble = PREAMBLE,
    tools = [tool::Health,],
    namespaces = ["evm-core"]
);
