//! Generated by `aomi-build gen-tool pelagos`. Each tool is a stub:
//! the wiring works (params → builder → send → JSON) but you should
//! review tool names, descriptions, and any auth assumptions.

use crate::client::Client as GenClient;
#[allow(unused_imports)]
use crate::client::types::*;
use aomi_sdk::schemars::JsonSchema;
use aomi_sdk::*;
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Default)]
pub(crate) struct PelagosApp;

fn ok<T: Serialize>(value: T) -> Result<Value, String> {
    let value = serde_json::to_value(value).map_err(|e| format!("[pelagos] serialize: {e}"))?;
    Ok(match value {
        Value::Object(mut m) => {
            m.insert("source".into(), Value::String("pelagos".into()));
            Value::Object(m)
        }
        other => serde_json::json!({ "source": "pelagos", "data": other }),
    })
}

fn rt() -> Result<tokio::runtime::Runtime, String> {
    tokio::runtime::Runtime::new().map_err(|e| format!("[pelagos] runtime: {e}"))
}

// ============================================================
// GET /health
// ============================================================

pub(crate) struct Health;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct HealthArgs {}

impl DynAomiTool for Health {
    type App = PelagosApp;
    type Args = HealthArgs;
    const NAME: &'static str = "pelagos_health";
    const DESCRIPTION: &'static str = "Liveness check for a Pelagos appchain node";

    fn run(_app: &PelagosApp, _args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let client = GenClient::new("http://localhost:8080");
        let runtime = rt()?;
        let result = runtime
            .block_on(async move { client.health().await })
            .map_err(|e| format!("[pelagos] health: {e}"))?;
        // Response: `HealthResponse` (typed). Project into a slim summary struct
        // before forwarding — every byte costs the LLM attention. Drop UI-only
        // fields (logoURI, audits, extensions); keep IDs / amounts / labels.
        ok(result.into_inner())
    }
}
