//! Generated by `aomi-build gen-tool dune`. Tool definitions are
//! starting points — edit `src/tool.rs` to refine names, descriptions, and
//! response shaping.

use aomi_sdk::*;

mod tool;

const PREAMBLE: &str = r##"## Role
You are an AI assistant for the dune API. Tools below wrap the official OpenAPI surface."##;

dyn_aomi_app!(
    app = tool::DuneApp,
    name = "dune",
    version = "0.1.0",
    preamble = PREAMBLE,
    tools = [
        tool::Postv1Dashboards,
        tool::Getv1DashboardsBySlugOwnerhandleSlug,
        tool::Getv1DashboardsDashboardid,
        tool::Patchv1DashboardsDashboardid,
        tool::Postv1DashboardsDashboardidArchive,
        tool::Getv1Datasets,
        tool::Postv1DatasetsSearch,
        tool::Postv1DatasetsSearchByContract,
        tool::Getv1DatasetsSlug,
        tool::Getv1EndpointsHandleEndpointslugResults,
        tool::Postv1ExecutionExecutionidCancel,
        tool::Getv1ExecutionExecutionidResults,
        tool::Getv1ExecutionExecutionidStatus,
        tool::Getv1MaterializedViews,
        tool::Postv1MaterializedViews,
        tool::Getv1MaterializedViewsName,
        tool::Deletev1MaterializedViewsName,
        tool::Postv1MaterializedViewsNameRefresh,
        tool::Postv1PipelinesExecute,
        tool::Getv1PipelinesExecutionsPipelineexecutionidStatus,
        tool::Getv1Queries,
        tool::Getv1QueriesQueryidVisualizations,
        tool::Postv1QueriesQueryidVisualizations,
        tool::Postv1Query,
        tool::Getv1QueryQueryid,
        tool::Patchv1QueryQueryid,
        tool::Postv1QueryQueryidArchive,
        tool::Postv1QueryQueryidPrivate,
        tool::Postv1QueryQueryidUnarchive,
        tool::Postv1QueryQueryidUnprivate,
        tool::Getv1QueryQueryidPipeline,
        tool::Postv1QueryQueryidPipelineExecute,
        tool::Getv1QueryQueryidResults,
        tool::Postv1SqlExecute,
        tool::Getv1Uploads,
        tool::Postv1Uploads,
        tool::Postv1UploadsCsv,
        tool::Deletev1UploadsNamespaceTablename,
        tool::Postv1UploadsNamespaceTablenameClear,
        tool::Postv1UploadsNamespaceTablenameInsert,
        tool::Postv1Usage,
        tool::Getv1VisualizationsVisualizationid,
        tool::Putv1VisualizationsVisualizationid,
        tool::Deletev1VisualizationsVisualizationid,
    ],
    namespaces = ["evm-core"]
);
