//! Generated by `aomi-build gen-tool dune`. Each tool is a stub:
//! the wiring works (params → builder → send → JSON) but you should
//! review tool names, descriptions, and any auth assumptions.

use aomi_ext::dune::Client as GenClient;
use aomi_sdk::*;
use aomi_sdk::schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Default)]
pub(crate) struct DuneApp;

fn ok<T: Serialize>(value: T) -> Result<Value, String> {
    let value = serde_json::to_value(value).map_err(|e| format!("[dune] serialize: {e}"))?;
    Ok(match value {
        Value::Object(mut m) => {
            m.insert("source".into(), Value::String("dune".into()));
            Value::Object(m)
        }
        other => serde_json::json!({ "source": "dune", "data": other }),
    })
}

fn rt() -> Result<tokio::runtime::Runtime, String> {
    tokio::runtime::Runtime::new().map_err(|e| format!("[dune] runtime: {e}"))
}

// ============================================================
// POST /v1/dashboards
// ============================================================

pub(crate) struct Postv1Dashboards;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1DashboardsArgs {
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Postv1Dashboards {
    type App = DuneApp;
    type Args = Postv1DashboardsArgs;
    const NAME: &'static str = "dune_postv1_dashboards";
    const DESCRIPTION: &'static str = "Create a dashboard";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_dashboards(api_key.as_str(), /* TODO: typed body */ todo!()).await
        }).map_err(|e| format!("[dune] postv1_dashboards: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/dashboards/by-slug/{owner_handle}/{slug}
// ============================================================

pub(crate) struct Getv1DashboardsBySlugOwnerhandleSlug;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1DashboardsBySlugOwnerhandleSlugArgs {
    /// Owner username or team handle
    pub owner_handle: String,
    /// Dashboard URL slug
    pub slug: String,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Getv1DashboardsBySlugOwnerhandleSlug {
    type App = DuneApp;
    type Args = Getv1DashboardsBySlugOwnerhandleSlugArgs;
    const NAME: &'static str = "dune_getv1_dashboards_by_slug_ownerhandle_slug";
    const DESCRIPTION: &'static str = "Get a dashboard by owner handle and slug";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_dashboards_by_slug_ownerhandle_slug(
                args.owner_handle.as_str(),
                args.slug.as_str(),
                api_key.as_str()
            ).await
        }).map_err(|e| format!("[dune] getv1_dashboards_by_slug_ownerhandle_slug: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/dashboards/{dashboard_id}
// ============================================================

pub(crate) struct Getv1DashboardsDashboardid;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1DashboardsDashboardidArgs {
    /// Dashboard ID
    pub dashboard_id: i64,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Getv1DashboardsDashboardid {
    type App = DuneApp;
    type Args = Getv1DashboardsDashboardidArgs;
    const NAME: &'static str = "dune_getv1_dashboards_dashboardid";
    const DESCRIPTION: &'static str = "Get a dashboard by ID";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_dashboards_dashboardid(args.dashboard_id, api_key.as_str()).await
        }).map_err(|e| format!("[dune] getv1_dashboards_dashboardid: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// PATCH /v1/dashboards/{dashboard_id}
// ============================================================

pub(crate) struct Patchv1DashboardsDashboardid;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Patchv1DashboardsDashboardidArgs {
    /// Dashboard ID
    pub dashboard_id: i64,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Patchv1DashboardsDashboardid {
    type App = DuneApp;
    type Args = Patchv1DashboardsDashboardidArgs;
    const NAME: &'static str = "dune_patchv1_dashboards_dashboardid";
    const DESCRIPTION: &'static str = "Update a dashboard";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.patchv1_dashboards_dashboardid(
                args.dashboard_id,
                api_key.as_str(),
                /* TODO: typed body */ todo!()
            ).await
        }).map_err(|e| format!("[dune] patchv1_dashboards_dashboardid: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/dashboards/{dashboard_id}/archive
// ============================================================

pub(crate) struct Postv1DashboardsDashboardidArchive;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1DashboardsDashboardidArchiveArgs {
    /// Dashboard ID
    pub dashboard_id: i64,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Postv1DashboardsDashboardidArchive {
    type App = DuneApp;
    type Args = Postv1DashboardsDashboardidArchiveArgs;
    const NAME: &'static str = "dune_postv1_dashboards_dashboardid_archive";
    const DESCRIPTION: &'static str = "Archive a dashboard";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_dashboards_dashboardid_archive(args.dashboard_id, api_key.as_str()).await
        }).map_err(|e| format!("[dune] postv1_dashboards_dashboardid_archive: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/datasets
// ============================================================

pub(crate) struct Getv1Datasets;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1DatasetsArgs {
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    /// Number of results to return (default 50, max 250)
    pub limit: Option<i64>,
    /// Offset for pagination
    pub offset: Option<i64>,
    /// Filter by owner handle
    pub owner_handle: Option<String>,
    /// Filter by dataset types (comma-separated: transformation_view, transformation_table, uploaded_table, decoded_table, spell, dune_table)
    pub type_: Option<String>,
}

impl DynAomiTool for Getv1Datasets {
    type App = DuneApp;
    type Args = Getv1DatasetsArgs;
    const NAME: &'static str = "dune_getv1_datasets";
    const DESCRIPTION: &'static str = "List datasets";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_datasets(
                Some(api_key.as_str()),
                args.limit,
                args.offset,
                args.owner_handle.as_deref(),
                args.type_.as_deref(),
                api_key.as_str()
            ).await
        }).map_err(|e| format!("[dune] getv1_datasets: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/datasets/search
// ============================================================

pub(crate) struct Postv1DatasetsSearch;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1DatasetsSearchArgs {
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Postv1DatasetsSearch {
    type App = DuneApp;
    type Args = Postv1DatasetsSearchArgs;
    const NAME: &'static str = "dune_postv1_datasets_search";
    const DESCRIPTION: &'static str = "Search datasets";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_datasets_search(
                Some(api_key.as_str()),
                api_key.as_str(),
                /* TODO: typed body */ todo!()
            ).await
        }).map_err(|e| format!("[dune] postv1_datasets_search: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/datasets/search-by-contract
// ============================================================

pub(crate) struct Postv1DatasetsSearchByContract;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1DatasetsSearchByContractArgs {
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Postv1DatasetsSearchByContract {
    type App = DuneApp;
    type Args = Postv1DatasetsSearchByContractArgs;
    const NAME: &'static str = "dune_postv1_datasets_search_by_contract";
    const DESCRIPTION: &'static str = "Search datasets by contract address";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_datasets_search_by_contract(
                Some(api_key.as_str()),
                api_key.as_str(),
                /* TODO: typed body */ todo!()
            ).await
        }).map_err(|e| format!("[dune] postv1_datasets_search_by_contract: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/datasets/{slug}
// ============================================================

pub(crate) struct Getv1DatasetsSlug;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1DatasetsSlugArgs {
    /// Dataset slug (e.g., 'dex.trades')
    pub slug: String,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Getv1DatasetsSlug {
    type App = DuneApp;
    type Args = Getv1DatasetsSlugArgs;
    const NAME: &'static str = "dune_getv1_datasets_slug";
    const DESCRIPTION: &'static str = "Get a dataset by slug";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_datasets_slug(args.slug.as_str(), Some(api_key.as_str()), api_key.as_str()).await
        }).map_err(|e| format!("[dune] getv1_datasets_slug: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/endpoints/{handle}/{endpoint_slug}/results
// ============================================================

pub(crate) struct Getv1EndpointsHandleEndpointslugResults;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1EndpointsHandleEndpointslugResultsArgs {
    /// Your user or team handle
    pub handle: String,
    /// The name of the endpoint as slug
    pub endpoint_slug: String,
    /// This enables returning a query result that was too large and only a partial result is
    pub allow_partial_results: Option<bool>,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    /// Specifies a comma-separated list of column names to return. If omitted, all columns are included.
    pub columns: Option<String>,
    /// Expression to filter out rows from the results to return. This expression is similar to
    pub filters: Option<String>,
    /// To bypass the default max credits per request limit, set ignore_max_credits_per_request=true
    pub ignore_max_credits_per_request: Option<bool>,
    /// Limit number of rows to return. This together with 'offset' allows easy pagination through
    pub limit: Option<i64>,
    /// Offset row number to start (inclusive, first row means offset=0) returning results
    pub offset: Option<i64>,
    pub query_id: i64,
    /// Number of rows to return from the result by sampling the data. This is useful when you
    pub sample_count: Option<i64>,
    /// Expression to define the order in which the results should be returned. This expression
    pub sort_by: Option<String>,
}

impl DynAomiTool for Getv1EndpointsHandleEndpointslugResults {
    type App = DuneApp;
    type Args = Getv1EndpointsHandleEndpointslugResultsArgs;
    const NAME: &'static str = "dune_getv1_endpoints_handle_endpointslug_results";
    const DESCRIPTION: &'static str = "Custom Endpoints";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_endpoints_handle_endpointslug_results(
                args.handle.as_str(),
                args.endpoint_slug.as_str(),
                args.allow_partial_results,
                Some(api_key.as_str()),
                args.columns.as_deref(),
                args.filters.as_deref(),
                args.ignore_max_credits_per_request,
                args.limit,
                args.offset,
                args.query_id,
                args.sample_count,
                args.sort_by.as_deref(),
                api_key.as_str()
            ).await
        }).map_err(|e| format!("[dune] getv1_endpoints_handle_endpointslug_results: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/execution/{execution_id}/cancel
// ============================================================

pub(crate) struct Postv1ExecutionExecutionidCancel;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1ExecutionExecutionidCancelArgs {
    /// The unique identifier of the execution
    pub execution_id: String,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Postv1ExecutionExecutionidCancel {
    type App = DuneApp;
    type Args = Postv1ExecutionExecutionidCancelArgs;
    const NAME: &'static str = "dune_postv1_execution_executionid_cancel";
    const DESCRIPTION: &'static str = "Cancel a triggered execution request given the execution ID";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_execution_executionid_cancel(
                args.execution_id.as_str(),
                Some(api_key.as_str()),
                api_key.as_str()
            ).await
        }).map_err(|e| format!("[dune] postv1_execution_executionid_cancel: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/execution/{execution_id}/results
// ============================================================

pub(crate) struct Getv1ExecutionExecutionidResults;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1ExecutionExecutionidResultsArgs {
    /// Execution ID
    pub execution_id: String,
    /// This enables returning a query result that was too large and only a partial result is
    pub allow_partial_results: Option<bool>,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    /// Specifies a comma-separated list of column names to return. If omitted, all columns are included.
    pub columns: Option<String>,
    /// Expression to filter out rows from the results to return. This expression is similar to
    pub filters: Option<String>,
    /// To bypass the default max credits per request limit, set ignore_max_credits_per_request=true
    pub ignore_max_credits_per_request: Option<bool>,
    /// Limit number of rows to return. This together with 'offset' allows easy pagination through
    pub limit: Option<i64>,
    /// Offset row number to start (inclusive, first row means offset=0) returning results
    pub offset: Option<i64>,
    /// Number of rows to return from the result by sampling the data. This is useful when you
    pub sample_count: Option<i64>,
    /// Expression to define the order in which the results should be returned. This expression
    pub sort_by: Option<String>,
}

impl DynAomiTool for Getv1ExecutionExecutionidResults {
    type App = DuneApp;
    type Args = Getv1ExecutionExecutionidResultsArgs;
    const NAME: &'static str = "dune_getv1_execution_executionid_results";
    const DESCRIPTION: &'static str = "Given an execution ID, returns result of a an execution request";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_execution_executionid_results(
                args.execution_id.as_str(),
                args.allow_partial_results,
                Some(api_key.as_str()),
                args.columns.as_deref(),
                args.filters.as_deref(),
                args.ignore_max_credits_per_request,
                args.limit,
                args.offset,
                args.sample_count,
                args.sort_by.as_deref(),
                api_key.as_str()
            ).await
        }).map_err(|e| format!("[dune] getv1_execution_executionid_results: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/execution/{execution_id}/status
// ============================================================

pub(crate) struct Getv1ExecutionExecutionidStatus;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1ExecutionExecutionidStatusArgs {
    /// Execution ID
    pub execution_id: String,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Getv1ExecutionExecutionidStatus {
    type App = DuneApp;
    type Args = Getv1ExecutionExecutionidStatusArgs;
    const NAME: &'static str = "dune_getv1_execution_executionid_status";
    const DESCRIPTION: &'static str = "Check the status of an execution request";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_execution_executionid_status(
                args.execution_id.as_str(),
                Some(api_key.as_str()),
                api_key.as_str()
            ).await
        }).map_err(|e| format!("[dune] getv1_execution_executionid_status: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/materialized-views
// ============================================================

pub(crate) struct Getv1MaterializedViews;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1MaterializedViewsArgs {
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    /// Number of materialized views to return on a page. Default and max 10000
    pub limit: Option<String>,
    /// Offset used for pagination. Use the value provided on a previous response under next_offset
    pub offset: Option<String>,
}

impl DynAomiTool for Getv1MaterializedViews {
    type App = DuneApp;
    type Args = Getv1MaterializedViewsArgs;
    const NAME: &'static str = "dune_getv1_materialized_views";
    const DESCRIPTION: &'static str = "This lists all materialized view owned by the account tied to the API key";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_materialized_views(
                Some(api_key.as_str()),
                args.limit.as_deref(),
                args.offset.as_deref(),
                api_key.as_str()
            ).await
        }).map_err(|e| format!("[dune] getv1_materialized_views: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/materialized-views
// ============================================================

pub(crate) struct Postv1MaterializedViews;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1MaterializedViewsArgs {
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Postv1MaterializedViews {
    type App = DuneApp;
    type Args = Postv1MaterializedViewsArgs;
    const NAME: &'static str = "dune_postv1_materialized_views";
    const DESCRIPTION: &'static str = "This upserts (create or replace) a materialized view from an existing query";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_materialized_views(
                Some(api_key.as_str()),
                api_key.as_str(),
                /* TODO: typed body */ todo!()
            ).await
        }).map_err(|e| format!("[dune] postv1_materialized_views: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/materialized-views/{name}
// ============================================================

pub(crate) struct Getv1MaterializedViewsName;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1MaterializedViewsNameArgs {
    /// Matview Name
    pub name: String,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Getv1MaterializedViewsName {
    type App = DuneApp;
    type Args = Getv1MaterializedViewsNameArgs;
    const NAME: &'static str = "dune_getv1_materialized_views_name";
    const DESCRIPTION: &'static str = "This fetches a materialized view given a name";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_materialized_views_name(args.name.as_str(), Some(api_key.as_str()), api_key.as_str()).await
        }).map_err(|e| format!("[dune] getv1_materialized_views_name: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// DELETE /v1/materialized-views/{name}
// ============================================================

pub(crate) struct Deletev1MaterializedViewsName;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Deletev1MaterializedViewsNameArgs {
    /// Matview Name
    pub name: String,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Deletev1MaterializedViewsName {
    type App = DuneApp;
    type Args = Deletev1MaterializedViewsNameArgs;
    const NAME: &'static str = "dune_deletev1_materialized_views_name";
    const DESCRIPTION: &'static str = "This deletes a materialized view given a full name";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.deletev1_materialized_views_name(args.name.as_str(), Some(api_key.as_str()), api_key.as_str()).await
        }).map_err(|e| format!("[dune] deletev1_materialized_views_name: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/materialized-views/{name}/refresh
// ============================================================

pub(crate) struct Postv1MaterializedViewsNameRefresh;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1MaterializedViewsNameRefreshArgs {
    /// Matview Name
    pub name: String,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Postv1MaterializedViewsNameRefresh {
    type App = DuneApp;
    type Args = Postv1MaterializedViewsNameRefreshArgs;
    const NAME: &'static str = "dune_postv1_materialized_views_name_refresh";
    const DESCRIPTION: &'static str = "This refreshes a materialized view";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_materialized_views_name_refresh(
                args.name.as_str(),
                Some(api_key.as_str()),
                api_key.as_str(),
                /* TODO: typed body */ todo!()
            ).await
        }).map_err(|e| format!("[dune] postv1_materialized_views_name_refresh: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/pipelines/execute
// ============================================================

pub(crate) struct Postv1PipelinesExecute;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1PipelinesExecuteArgs {
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Postv1PipelinesExecute {
    type App = DuneApp;
    type Args = Postv1PipelinesExecuteArgs;
    const NAME: &'static str = "dune_postv1_pipelines_execute";
    const DESCRIPTION: &'static str = "Execute a pipeline";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_pipelines_execute(
                Some(api_key.as_str()),
                api_key.as_str(),
                /* TODO: typed body */ todo!()
            ).await
        }).map_err(|e| format!("[dune] postv1_pipelines_execute: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/pipelines/executions/{pipeline_execution_id}/status
// ============================================================

pub(crate) struct Getv1PipelinesExecutionsPipelineexecutionidStatus;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1PipelinesExecutionsPipelineexecutionidStatusArgs {
    /// Unique identifier of the pipeline execution
    pub pipeline_execution_id: String,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Getv1PipelinesExecutionsPipelineexecutionidStatus {
    type App = DuneApp;
    type Args = Getv1PipelinesExecutionsPipelineexecutionidStatusArgs;
    const NAME: &'static str = "dune_getv1_pipelines_executions_pipelineexecutionid_status";
    const DESCRIPTION: &'static str = "Get pipeline execution status";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_pipelines_executions_pipelineexecutionid_status(
                args.pipeline_execution_id.as_str(),
                Some(api_key.as_str()),
                api_key.as_str()
            ).await
        }).map_err(|e| format!("[dune] getv1_pipelines_executions_pipelineexecutionid_status: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/queries
// ============================================================

pub(crate) struct Getv1Queries;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1QueriesArgs {
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    /// Number of queries to return on a page. Default: 20
    pub limit: Option<i64>,
    /// Offset used for pagination. Default: 0
    pub offset: Option<i64>,
}

impl DynAomiTool for Getv1Queries {
    type App = DuneApp;
    type Args = Getv1QueriesArgs;
    const NAME: &'static str = "dune_getv1_queries";
    const DESCRIPTION: &'static str = "List queries";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_queries(Some(api_key.as_str()), args.limit, args.offset, api_key.as_str()).await
        }).map_err(|e| format!("[dune] getv1_queries: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/queries/{query_id}/visualizations
// ============================================================

pub(crate) struct Getv1QueriesQueryidVisualizations;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1QueriesQueryidVisualizationsArgs {
    /// Query ID
    pub query_id: i64,
    /// Max results to return (default 25, max 100)
    pub limit: Option<i64>,
    /// Pagination offset (default 0)
    pub offset: Option<i64>,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Getv1QueriesQueryidVisualizations {
    type App = DuneApp;
    type Args = Getv1QueriesQueryidVisualizationsArgs;
    const NAME: &'static str = "dune_getv1_queries_queryid_visualizations";
    const DESCRIPTION: &'static str = "List visualizations for a query";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_queries_queryid_visualizations(args.query_id, args.limit, args.offset, api_key.as_str()).await
        }).map_err(|e| format!("[dune] getv1_queries_queryid_visualizations: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/queries/{query_id}/visualizations
// ============================================================

pub(crate) struct Postv1QueriesQueryidVisualizations;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1QueriesQueryidVisualizationsArgs {
    /// Query ID
    pub query_id: i64,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Postv1QueriesQueryidVisualizations {
    type App = DuneApp;
    type Args = Postv1QueriesQueryidVisualizationsArgs;
    const NAME: &'static str = "dune_postv1_queries_queryid_visualizations";
    const DESCRIPTION: &'static str = "Create a visualization on an existing query";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_queries_queryid_visualizations(args.query_id, api_key.as_str(), /* TODO: typed body */ todo!()).await
        }).map_err(|e| format!("[dune] postv1_queries_queryid_visualizations: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/query
// ============================================================

pub(crate) struct Postv1Query;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1QueryArgs {
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Postv1Query {
    type App = DuneApp;
    type Args = Postv1QueryArgs;
    const NAME: &'static str = "dune_postv1_query";
    const DESCRIPTION: &'static str = "Create and save a query on Dune";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_query(
                Some(api_key.as_str()),
                api_key.as_str(),
                /* TODO: typed body */ todo!()
            ).await
        }).map_err(|e| format!("[dune] postv1_query: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/query/{queryId}
// ============================================================

pub(crate) struct Getv1QueryQueryid;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1QueryQueryidArgs {
    /// Query ID
    pub query_id: i64,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Getv1QueryQueryid {
    type App = DuneApp;
    type Args = Getv1QueryQueryidArgs;
    const NAME: &'static str = "dune_getv1_query_queryid";
    const DESCRIPTION: &'static str = "Returns the details of a query on Dune";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_query_queryid(args.query_id, Some(api_key.as_str()), api_key.as_str()).await
        }).map_err(|e| format!("[dune] getv1_query_queryid: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// PATCH /v1/query/{queryId}
// ============================================================

pub(crate) struct Patchv1QueryQueryid;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Patchv1QueryQueryidArgs {
    /// Query ID
    pub query_id: i64,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Patchv1QueryQueryid {
    type App = DuneApp;
    type Args = Patchv1QueryQueryidArgs;
    const NAME: &'static str = "dune_patchv1_query_queryid";
    const DESCRIPTION: &'static str = "Update the details of a query on Dune";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.patchv1_query_queryid(args.query_id, Some(api_key.as_str()), api_key.as_str()).await
        }).map_err(|e| format!("[dune] patchv1_query_queryid: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/query/{queryId}/archive
// ============================================================

pub(crate) struct Postv1QueryQueryidArchive;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1QueryQueryidArchiveArgs {
    /// Query ID
    pub query_id: i64,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Postv1QueryQueryidArchive {
    type App = DuneApp;
    type Args = Postv1QueryQueryidArchiveArgs;
    const NAME: &'static str = "dune_postv1_query_queryid_archive";
    const DESCRIPTION: &'static str = "Archive Query on Dune";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_query_queryid_archive(args.query_id, Some(api_key.as_str()), api_key.as_str()).await
        }).map_err(|e| format!("[dune] postv1_query_queryid_archive: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/query/{queryId}/private
// ============================================================

pub(crate) struct Postv1QueryQueryidPrivate;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1QueryQueryidPrivateArgs {
    /// Query ID
    pub query_id: i64,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Postv1QueryQueryidPrivate {
    type App = DuneApp;
    type Args = Postv1QueryQueryidPrivateArgs;
    const NAME: &'static str = "dune_postv1_query_queryid_private";
    const DESCRIPTION: &'static str = "Private Query on Dune";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_query_queryid_private(args.query_id, Some(api_key.as_str()), api_key.as_str()).await
        }).map_err(|e| format!("[dune] postv1_query_queryid_private: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/query/{queryId}/unarchive
// ============================================================

pub(crate) struct Postv1QueryQueryidUnarchive;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1QueryQueryidUnarchiveArgs {
    /// Query ID
    pub query_id: i64,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Postv1QueryQueryidUnarchive {
    type App = DuneApp;
    type Args = Postv1QueryQueryidUnarchiveArgs;
    const NAME: &'static str = "dune_postv1_query_queryid_unarchive";
    const DESCRIPTION: &'static str = "Unarchive Query on Dune";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_query_queryid_unarchive(args.query_id, Some(api_key.as_str()), api_key.as_str()).await
        }).map_err(|e| format!("[dune] postv1_query_queryid_unarchive: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/query/{queryId}/unprivate
// ============================================================

pub(crate) struct Postv1QueryQueryidUnprivate;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1QueryQueryidUnprivateArgs {
    /// Query ID
    pub query_id: i64,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Postv1QueryQueryidUnprivate {
    type App = DuneApp;
    type Args = Postv1QueryQueryidUnprivateArgs;
    const NAME: &'static str = "dune_postv1_query_queryid_unprivate";
    const DESCRIPTION: &'static str = "Unprivate a query on Dune";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_query_queryid_unprivate(args.query_id, Some(api_key.as_str()), api_key.as_str()).await
        }).map_err(|e| format!("[dune] postv1_query_queryid_unprivate: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/query/{query_id}/pipeline
// ============================================================

pub(crate) struct Getv1QueryQueryidPipeline;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1QueryQueryidPipelineArgs {
    /// Unique identifier of the query
    pub query_id: i64,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    /// The performance engine tier. Can be `small`, `medium`, or `large`.
    pub performance: Option<String>,
    /// SQL Query parameters in json key-value pairs
    pub query_parameters: Option<String>,
}

impl DynAomiTool for Getv1QueryQueryidPipeline {
    type App = DuneApp;
    type Args = Getv1QueryQueryidPipelineArgs;
    const NAME: &'static str = "dune_getv1_query_queryid_pipeline";
    const DESCRIPTION: &'static str = "Get query pipeline";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_query_queryid_pipeline(
                args.query_id,
                Some(api_key.as_str()),
                args.performance.as_deref(),
                args.query_parameters.as_deref(),
                api_key.as_str()
            ).await
        }).map_err(|e| format!("[dune] getv1_query_queryid_pipeline: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/query/{query_id}/pipeline/execute
// ============================================================

pub(crate) struct Postv1QueryQueryidPipelineExecute;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1QueryQueryidPipelineExecuteArgs {
    /// Unique identifier of the query
    pub query_id: i64,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Postv1QueryQueryidPipelineExecute {
    type App = DuneApp;
    type Args = Postv1QueryQueryidPipelineExecuteArgs;
    const NAME: &'static str = "dune_postv1_query_queryid_pipeline_execute";
    const DESCRIPTION: &'static str = "Execute a query pipeline";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_query_queryid_pipeline_execute(
                args.query_id,
                Some(api_key.as_str()),
                api_key.as_str(),
                /* TODO: typed body */ todo!()
            ).await
        }).map_err(|e| format!("[dune] postv1_query_queryid_pipeline_execute: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/query/{query_id}/results
// ============================================================

pub(crate) struct Getv1QueryQueryidResults;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1QueryQueryidResultsArgs {
    /// Query ID
    pub query_id: String,
    /// This enables returning a query result that was too large and only a partial result is
    pub allow_partial_results: Option<bool>,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    /// Specifies a comma-separated list of column names to return. If omitted, all columns are included.
    pub columns: Option<String>,
    /// Expression to filter out rows from the results to return. This expression is similar to
    pub filters: Option<String>,
    /// To bypass the default max credits per request limit, set ignore_max_credits_per_request=true
    pub ignore_max_credits_per_request: Option<bool>,
    /// Limit number of rows to return. This together with 'offset' allows easy pagination through
    pub limit: Option<i64>,
    /// Offset row number to start (inclusive, first row means offset=0) returning results
    pub offset: Option<i64>,
    /// Number of rows to return from the result by sampling the data. This is useful when you
    pub sample_count: Option<i64>,
    /// Expression to define the order in which the results should be returned. This expression
    pub sort_by: Option<String>,
}

impl DynAomiTool for Getv1QueryQueryidResults {
    type App = DuneApp;
    type Args = Getv1QueryQueryidResultsArgs;
    const NAME: &'static str = "dune_getv1_query_queryid_results";
    const DESCRIPTION: &'static str = "Get Latest Query Result";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_query_queryid_results(
                args.query_id.as_str(),
                args.allow_partial_results,
                Some(api_key.as_str()),
                args.columns.as_deref(),
                args.filters.as_deref(),
                args.ignore_max_credits_per_request,
                args.limit,
                args.offset,
                args.sample_count,
                args.sort_by.as_deref(),
                api_key.as_str()
            ).await
        }).map_err(|e| format!("[dune] getv1_query_queryid_results: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/sql/execute
// ============================================================

pub(crate) struct Postv1SqlExecute;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1SqlExecuteArgs {
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Postv1SqlExecute {
    type App = DuneApp;
    type Args = Postv1SqlExecuteArgs;
    const NAME: &'static str = "dune_postv1_sql_execute";
    const DESCRIPTION: &'static str = "Execute raw SQL query";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_sql_execute(
                Some(api_key.as_str()),
                api_key.as_str(),
                /* TODO: typed body */ todo!()
            ).await
        }).map_err(|e| format!("[dune] postv1_sql_execute: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/uploads
// ============================================================

pub(crate) struct Getv1Uploads;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1UploadsArgs {
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    /// Number of tables to return on a page. Default: 50, max: 10000
    pub limit: Option<i32>,
    /// Offset used for pagination. Negative values are treated as 0
    pub offset: Option<i32>,
}

impl DynAomiTool for Getv1Uploads {
    type App = DuneApp;
    type Args = Getv1UploadsArgs;
    const NAME: &'static str = "dune_getv1_uploads";
    const DESCRIPTION: &'static str = "List all tables owned by the account";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_uploads(Some(api_key.as_str()), args.limit, args.offset, api_key.as_str()).await
        }).map_err(|e| format!("[dune] getv1_uploads: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/uploads
// ============================================================

pub(crate) struct Postv1Uploads;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1UploadsArgs {
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Postv1Uploads {
    type App = DuneApp;
    type Args = Postv1UploadsArgs;
    const NAME: &'static str = "dune_postv1_uploads";
    const DESCRIPTION: &'static str = "Create an empty uploaded table with a defined schema";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_uploads(
                Some(api_key.as_str()),
                api_key.as_str(),
                /* TODO: typed body */ todo!()
            ).await
        }).map_err(|e| format!("[dune] postv1_uploads: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/uploads/csv
// ============================================================

pub(crate) struct Postv1UploadsCsv;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1UploadsCsvArgs {
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Postv1UploadsCsv {
    type App = DuneApp;
    type Args = Postv1UploadsCsvArgs;
    const NAME: &'static str = "dune_postv1_uploads_csv";
    const DESCRIPTION: &'static str = "Upload CSV file as a table";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_uploads_csv(
                Some(api_key.as_str()),
                api_key.as_str(),
                /* TODO: typed body */ todo!()
            ).await
        }).map_err(|e| format!("[dune] postv1_uploads_csv: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// DELETE /v1/uploads/{namespace}/{table_name}
// ============================================================

pub(crate) struct Deletev1UploadsNamespaceTablename;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Deletev1UploadsNamespaceTablenameArgs {
    /// The namespace of the table to delete
    pub namespace: String,
    /// The table name of the table to delete
    pub table_name: String,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Deletev1UploadsNamespaceTablename {
    type App = DuneApp;
    type Args = Deletev1UploadsNamespaceTablenameArgs;
    const NAME: &'static str = "dune_deletev1_uploads_namespace_tablename";
    const DESCRIPTION: &'static str = "Delete an uploaded table";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.deletev1_uploads_namespace_tablename(
                args.namespace.as_str(),
                args.table_name.as_str(),
                Some(api_key.as_str()),
                api_key.as_str()
            ).await
        }).map_err(|e| format!("[dune] deletev1_uploads_namespace_tablename: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/uploads/{namespace}/{table_name}/clear
// ============================================================

pub(crate) struct Postv1UploadsNamespaceTablenameClear;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1UploadsNamespaceTablenameClearArgs {
    /// The namespace of the table to clear
    pub namespace: String,
    /// The table name of the table to clear
    pub table_name: String,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Postv1UploadsNamespaceTablenameClear {
    type App = DuneApp;
    type Args = Postv1UploadsNamespaceTablenameClearArgs;
    const NAME: &'static str = "dune_postv1_uploads_namespace_tablename_clear";
    const DESCRIPTION: &'static str = "Clear all data from an uploaded table";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_uploads_namespace_tablename_clear(
                args.namespace.as_str(),
                args.table_name.as_str(),
                Some(api_key.as_str()),
                api_key.as_str()
            ).await
        }).map_err(|e| format!("[dune] postv1_uploads_namespace_tablename_clear: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/uploads/{namespace}/{table_name}/insert
// ============================================================

pub(crate) struct Postv1UploadsNamespaceTablenameInsert;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1UploadsNamespaceTablenameInsertArgs {
    /// The namespace of the table
    pub namespace: String,
    /// The table name
    pub table_name: String,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    /// Content type: text/csv or application/x-ndjson
    pub content_type: String,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Postv1UploadsNamespaceTablenameInsert {
    type App = DuneApp;
    type Args = Postv1UploadsNamespaceTablenameInsertArgs;
    const NAME: &'static str = "dune_postv1_uploads_namespace_tablename_insert";
    const DESCRIPTION: &'static str = "Insert data into an uploaded table";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_uploads_namespace_tablename_insert(
                args.namespace.as_str(),
                args.table_name.as_str(),
                Some(api_key.as_str()),
                args.content_type.as_str(),
                api_key.as_str(),
                /* TODO: typed body */ todo!()
            ).await
        }).map_err(|e| format!("[dune] postv1_uploads_namespace_tablename_insert: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// POST /v1/usage
// ============================================================

pub(crate) struct Postv1Usage;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Postv1UsageArgs {
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Postv1Usage {
    type App = DuneApp;
    type Args = Postv1UsageArgs;
    const NAME: &'static str = "dune_postv1_usage";
    const DESCRIPTION: &'static str = "Get Usage Data";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.postv1_usage(
                Some(api_key.as_str()),
                api_key.as_str(),
                /* TODO: typed body */ todo!()
            ).await
        }).map_err(|e| format!("[dune] postv1_usage: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// GET /v1/visualizations/{visualization_id}
// ============================================================

pub(crate) struct Getv1VisualizationsVisualizationid;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Getv1VisualizationsVisualizationidArgs {
    /// Visualization ID
    pub visualization_id: i64,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Getv1VisualizationsVisualizationid {
    type App = DuneApp;
    type Args = Getv1VisualizationsVisualizationidArgs;
    const NAME: &'static str = "dune_getv1_visualizations_visualizationid";
    const DESCRIPTION: &'static str = "Get a visualization by ID";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getv1_visualizations_visualizationid(args.visualization_id, api_key.as_str()).await
        }).map_err(|e| format!("[dune] getv1_visualizations_visualizationid: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// PUT /v1/visualizations/{visualization_id}
// ============================================================

pub(crate) struct Putv1VisualizationsVisualizationid;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Putv1VisualizationsVisualizationidArgs {
    /// Visualization ID
    pub visualization_id: i64,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
    // TODO: typed body — generated client expects aomi_ext::dune::types::*.
    // Add `pub body: <T>` and edit `run` to pass it to req.body(...).
}

impl DynAomiTool for Putv1VisualizationsVisualizationid {
    type App = DuneApp;
    type Args = Putv1VisualizationsVisualizationidArgs;
    const NAME: &'static str = "dune_putv1_visualizations_visualizationid";
    const DESCRIPTION: &'static str = "Update a visualization";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.putv1_visualizations_visualizationid(
                args.visualization_id,
                api_key.as_str(),
                /* TODO: typed body */ todo!()
            ).await
        }).map_err(|e| format!("[dune] putv1_visualizations_visualizationid: {e}"))?;
        ok(result.into_inner())
    }
}

// ============================================================
// DELETE /v1/visualizations/{visualization_id}
// ============================================================

pub(crate) struct Deletev1VisualizationsVisualizationid;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct Deletev1VisualizationsVisualizationidArgs {
    /// Visualization ID
    pub visualization_id: i64,
    /// API credential (falls back to env var DUNE_API_KEY).
    pub api_key: Option<String>,
}

impl DynAomiTool for Deletev1VisualizationsVisualizationid {
    type App = DuneApp;
    type Args = Deletev1VisualizationsVisualizationidArgs;
    const NAME: &'static str = "dune_deletev1_visualizations_visualizationid";
    const DESCRIPTION: &'static str = "Delete a visualization";

    fn run(_app: &DuneApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let api_key = resolve_secret_value(args.api_key.as_deref(), "DUNE_API_KEY", "[dune] missing api_key argument and DUNE_API_KEY env var")?;
        let client = GenClient::new("https://api.dune.com/api");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.deletev1_visualizations_visualizationid(args.visualization_id, api_key.as_str()).await
        }).map_err(|e| format!("[dune] deletev1_visualizations_visualizationid: {e}"))?;
        ok(result.into_inner())
    }
}

