//! Generated by `aomi-build gen-tool cow`. Tool definitions are
//! starting points — edit `src/tool.rs` to refine names, descriptions, and
//! response shaping.

use aomi_sdk::*;

mod tool;

const PREAMBLE: &str = r##"## Role
You are an AI assistant for the cow API. Tools below wrap the official OpenAPI surface."##;

dyn_aomi_app!(
    app = tool::CowApp,
    name = "cow",
    version = "0.1.0",
    preamble = PREAMBLE,
    tools = [
        tool::GetpublicHistory,
    ],
    namespaces = ["evm-core"]
);
