//! Generated by `aomi-build gen-tool cow`. Each tool is a stub:
//! the wiring works (params → builder → send → JSON) but you should
//! review tool names, descriptions, and any auth assumptions.

use aomi_ext::cow::Client as GenClient;
use aomi_sdk::*;
use aomi_sdk::schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Default)]
pub(crate) struct CowApp;

fn ok<T: Serialize>(value: T) -> Result<Value, String> {
    let value = serde_json::to_value(value).map_err(|e| format!("[cow] serialize: {e}"))?;
    Ok(match value {
        Value::Object(mut m) => {
            m.insert("source".into(), Value::String("cow".into()));
            Value::Object(m)
        }
        other => serde_json::json!({ "source": "cow", "data": other }),
    })
}

fn rt() -> Result<tokio::runtime::Runtime, String> {
    tokio::runtime::Runtime::new().map_err(|e| format!("[cow] runtime: {e}"))
}

// ============================================================
// GET /public/history
// ============================================================

pub(crate) struct GetpublicHistory;

#[derive(Debug, Deserialize, JsonSchema)]
pub(crate) struct GetpublicHistoryArgs {
    /// Startdatum der Abfrage im Format (JJJJ-MM-DD)
    pub from: Option<String>,
    /// Ortssuche mit Freitext
    pub q: Option<String>,
    /// Enddatum der Abfrage im Format (JJJJ-MM-DD)
    pub to: Option<String>,
}

impl DynAomiTool for GetpublicHistory {
    type App = CowApp;
    type Args = GetpublicHistoryArgs;
    const NAME: &'static str = "cow_getpublic_history";
    const DESCRIPTION: &'static str = "Wetter 2021 für Berlin, Reichstag";

    fn run(_app: &CowApp, args: Self::Args, _ctx: DynToolCallCtx) -> Result<Value, String> {
        let client = GenClient::new("https://api.ecowetter.de");
        let runtime = rt()?;
        let result = runtime.block_on(async move {
            client.getpublic_history(args.from.as_deref(), args.q.as_deref(), args.to.as_deref()).await
        }).map_err(|e| format!("[cow] getpublic_history: {e}"))?;
        ok(result.into_inner())
    }
}

