//! Generated by `aomi-build gen-client across`.
//! Do not edit by hand — re-run with --force to regenerate.
//!
//! Hand-written companions (signing helpers, etc.) live next to this file
//! in `auth.rs` or other sibling modules.

#[allow(clippy::all, dead_code, unused_imports)]
pub mod client;

pub use client::*;
